(function(_ds){var window=this;'use strict';var mI=function(){var a=_ds.T.call(this)||this;a.K=null;a.C=!1;a.j=null;a.h=null;a.m=new _ds.Bj;a.D=null;a.H=new Promise(function(b){a.D=b});a.G=new _ds.yj(function(){kI(a)},15);a.F=new _ds.yj(function(){lI(a)},20);a.o=new Set;return a},oI=function(a,b){b=Array.from((void 0===b?a:b).querySelectorAll(".devsite-nav-title"));a.o=new Set(b);if(_ds.li().hash){b=new _ds.Bs;a=_ds.p(a.o);for(var c=a.next();!c.done;c=a.next())_ds.Ds(b,c.value)}else nI(a,a.o)},nI=function(a,b){var c,d;_ds.E(function(e){if(1==
e.h)return _ds.w(e,DevsiteApp.whenReady(),2);c=new _ds.Bs;d=function(g){g=g.target;_ds.Ds(c,g);a.o.delete(g);DevsiteApp.unregisterIntersectionForElement(g)};b.forEach(function(g){try{DevsiteApp.registerIntersectionForElement(g,d)}catch(k){d({target:g})}});_ds.x(e)})},lI=function(a){a=0<a.getElementsByClassName("devsite-nav-item").length;var b=document.getElementById("devsite-hamburger-menu");b&&(a?b.removeAttribute("visually-hidden"):b.setAttribute("visually-hidden",""))},sI=function(a){a.m.listen(a,
"click",function(b){if(!b.defaultPrevented){var c=b.target;"devsite-close-nav"===c.getAttribute("id")&&(b.preventDefault(),b.stopPropagation(),a.scrollTop=0,a.hasAttribute("top-level-nav")?a.dispatchEvent(new CustomEvent("devsite-sitemask-hide",{bubbles:!0})):a.setAttribute("top-level-nav",""));if(c.hasAttribute("menu")){var d=c.getAttribute("menu");d&&pI(a,d)&&(b.preventDefault(),b.stopPropagation(),a.scrollTop=0,a.removeAttribute("top-level-nav"))}if(!(c.classList.contains("devsite-nav-toggle")||
c.classList.contains("devsite-nav-title-no-path")||c.parentElement.classList.contains("devsite-nav-title-no-path"))){a.j&&(b=a.j.querySelector("[menu=_book]"))&&b.contains(c)&&a.dispatchEvent(new CustomEvent("devsite-sitemask-hide",{bubbles:!0}));var e;c instanceof Element&&c.matches("a.devsite-nav-title")?e=c:e=_ds.ph(c,"a","devsite-nav-title");e&&!e.classList.contains("devsite-nav-has-children")&&a.dispatchEvent(new CustomEvent("devsite-sitemask-hide",{bubbles:!0}))}}});a.m.listen(a,[qI,"focusin"],
function(b){return void rI(a,b)});a.m.listen(document.body,"devsite-sitemask-hidden",function(){a.j&&(pI(a,"_book")?a.removeAttribute("top-level-nav"):a.setAttribute("top-level-nav",""))});a.m.listen(document.body,"devsite-page-loaded",function(){return void a.F.qa()});a.m.listen(a,"devsite-content-updated",function(){a.F.qa();a.G.qa()});a.m.listen(a,"scroll",function(){return a.C=!0})},pI=function(a,b){var c=!1;Array.from(a.j.querySelectorAll("[menu]")).forEach(function(d){d.getAttribute("menu")===
b?(d.removeAttribute("hidden"),c=!0):d.setAttribute("hidden","")});return c},rI=function(a,b){b.defaultPrevented||(b=_ds.oh(b.target,function(c){return c instanceof HTMLAnchorElement&&c.hasAttribute("href")||c===a},!0),b!==a&&_ds.Ed(b,_ds.si(b.href).href))},tI=function(a){_ds.E(function(b){switch(b.h){case 1:return a.C=!1,_ds.w(b,_ds.zi(),2);case 2:return kI(a),_ds.w(b,a.H,3);case 3:return _ds.w(b,DevsiteApp.whenReady(),4);case 4:return _ds.w(b,_ds.zi(),5);case 5:kI(a),_ds.x(b)}})},uI=function(a,
b){(b=void 0===b?a:b)||(b=a);Array.from(b.getElementsByClassName("devsite-nav-active")).forEach(function(c){c.classList.remove("devsite-nav-active")});a=_ds.Di(_ds.li().pathname);a='[href="'+_ds.si(a).href+'"], [href="'+a+'"],\n        [alt-paths*=" '+a+' "]';Array.from(b.querySelectorAll(a)).forEach(function(c){c.classList.add("devsite-nav-active")})},vI=function(a,b){(b=void 0===b?a:b)||(b=a);var c=b.getElementsByClassName("devsite-mobile-nav-bottom")[0];if(c){var d=c.getElementsByClassName("devsite-nav-active")[0];
if(d)for(;d.parentNode&&d.parentNode!=b;)d.hasAttribute("collapsed")&&(d.removeAttribute("animatable"),_ds.Fj(a.m,d,"devsite-expandable-nav-transition-end",function(){d.setAttribute("animatable","")}),d.removeAttribute("collapsed")),d=d.parentNode}},kI=function(a){var b;_ds.E(function(c){if(1==c.h)return a.j?_ds.w(c,DevsiteApp.whenReady(),2):c.return();if(b=a.j.getElementsByClassName("devsite-nav-active")[0])a.C||wI(a,b),a.setAttribute("animatable","");_ds.x(c)})},wI=function(a,b){var c,d;_ds.E(function(e){if(1==
e.h)return c=a.C,"scrollIntoViewIfNeeded"in b?b.scrollIntoViewIfNeeded():(d=_ds.Uj(b,a,!0),a.scrollTop=d.y),_ds.w(e,_ds.zi(),2);a.C=c;_ds.x(e)})},xI=function(a){var b,c,d;_ds.E(function(e){if(1==e.h)return _ds.w(e,DevsiteApp.whenReady(),2);b=_ds.p(a.o);for(c=b.next();!c.done;c=b.next())d=c.value,DevsiteApp.unregisterIntersectionForElement(d);_ds.x(e)})},qI="onpointerover"in window?"pointerover":"mouseover";_ds.u(mI,_ds.T);_ds.f=mI.prototype;
_ds.f.connectedCallback=function(){this.h||(this.h=document.createElement("div"),this.h.classList.add("devsite-book-nav-bg"));_ds.Ng(this.h,this);lI(this);sI(this);this.Ha();this.setAttribute("animatable","");oI(this)};_ds.f.disconnectedCallback=function(){_ds.Hj(this.m);xI(this);this.o.clear();var a=document.getElementById("devsite-hamburger-menu");a&&a.setAttribute("visually-hidden","");this.h&&_ds.Qg(this.h);this.removeAttribute("animatable")};
_ds.f.attributeChangedCallback=function(a){if("hidden"==a){var b=this.hasAttribute("hidden");this.dispatchEvent(new CustomEvent(b?"devsite-element-hidden":"devsite-element-visible",{bubbles:!0}));var c=document.getElementsByClassName("devsite-main-content")[0];c&&(b?c.removeAttribute("has-book-nav"):c.setAttribute("has-book-nav",""))}if("fixed"==a||"hidden"==a)b=this.hasAttribute(a),this.h&&(b?this.h.setAttribute(a,""):this.h.removeAttribute(a));"fixed"==a&&this.D()};
_ds.f.Ha=function(a){var b=this;a=void 0===a?!0:a;this.K=this.getElementsByClassName("devsite-book-nav")[0];this.j=this.getElementsByClassName("devsite-mobile-nav-bottom")[0];this.setAttribute("top-level-nav","");this.j&&this.j.querySelector("[menu=_book]")&&this.removeAttribute("top-level-nav");0===this.children.length&&this.setAttribute("hidden","");!this.hasAttribute("hidden")&&a&&(uI(this),vI(this),tI(this));this.h&&["hidden","fixed"].forEach(function(c){b.hasAttribute(c)&&b.h.setAttribute(c,
"")});!this.hasAttribute("hidden")&&this.j&&this.j.getElementsByClassName("devsite-nav-active")[0]||this.setAttribute("animatable","")};_ds.f.updateContent=function(a){var b=this;a?(this.removeAttribute("animatable"),a=a.querySelector("nav"),uI(this,a),vI(this,a),a&&(xI(this),this.o.clear(),oI(this,a)),_ds.yl(this,this.getElementsByTagName("nav")[0],a),this.G.qa()):_ds.Mg(this);window.requestAnimationFrame(function(){b.Ha(!1)})};
_ds.l.Object.defineProperties(mI,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return["hidden","fixed"]}}});mI.prototype.updateContent=mI.prototype.updateContent;mI.prototype.attributeChangedCallback=mI.prototype.attributeChangedCallback;mI.prototype.disconnectedCallback=mI.prototype.disconnectedCallback;mI.prototype.connectedCallback=mI.prototype.connectedCallback;try{window.customElements.define("devsite-book-nav",mI)}catch(a){console.warn("devsite.app.customElement.DevsiteBookNav",a)};})(_ds_www);
