(function(_ds){var window=this;'use strict';var NI=function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c];if(_ds.mb(d)){var e=a.length||0,g=d.length||0;a.length=e+g;for(var k=0;k<g;k++)a[e+k]=d[k]}else a.push(d)}},OI=function(){var a=new _ds.bs;NI(a.L,"data-devsite-credential-type data-modal-dialog-id data-scope data-terminal-prefix data-title data-type".split(" "));return a},PI=function(){var a=OI();_ds.fd(["devsite-var"],function(b){this.K.push(b)},a);return a},QI=function(){return(0,_ds.W)('<div class="devsite-code-buttons-container"></div>')},
RI=function(a){a=a.label;return(0,_ds.W)('<button type="button" class="gc-analytics-event material-icons devsite-icon-code-dark devsite-toggle-dark" data-category="Site-Wide Custom Events" data-label="Dark Code Toggle" track-type="exampleCode" track-name="darkCodeToggle" aria-label="'+_ds.Z(a)+'" data-title="'+_ds.Z(a)+'"></button>')},SI=function(a){a=a.label;return(0,_ds.W)('<button type="button" class="gc-analytics-event material-icons devsite-icon-code-light devsite-toggle-light" data-category="Site-Wide Custom Events" data-label="Light Code Toggle" track-type="exampleCode" track-name="lightCodeToggle" aria-label="'+
_ds.Z(a)+'" data-title="'+_ds.Z(a)+'"></button>')},TI=function(a){var b=a.label;return(0,_ds.W)('<button type="button" class="gc-analytics-event material-icons devsite-icon-copy" data-category="Site-Wide Custom Events" data-label="'+_ds.Z(a.vl)+'" track-type="exampleCode" track-name="clickToCopy" aria-label="'+_ds.Z(b)+'" data-title="'+_ds.Z(b)+'"></button>')},UI=function(a){a=a.label;return(0,_ds.W)('<button type="button" class="gc-analytics-event material-icons devsite-icon-code" data-category="jsfiddle" data-label="" track-type="exampleCode" track-name="jsfiddle" aria-label="'+
_ds.Z(a)+'" data-title="'+_ds.Z(a)+'"></button>')},VI=function(){var a=_ds.T.call(this,["devsite-snackbar"])||this;a.h=null;a.m=null;a.G="";a.C=null;a.j=new _ds.Bj;a.K=!1;a.o=null;a.D=null;a.L=new _ds.zl;a.M=new _ds.fs(_ds.ls(PI()));a.F=null;a.H=new _ds.$q;return a},WI=function(a){Array.from(a.getElementsByClassName("prettyprint")).forEach(function(b){b.classList.remove("prettyprint");var c=(c=b.className.match(/\blang(?:uage)?-([\w.]+)(?!\S)/))?c[1]:void 0;c=window.prettyPrintOne(b.innerHTML,c);
c=_ds.xs(a.M,c);_ds.Cd(b,c);b.getElementsByTagName("strong").length&&b.classList.add("devsite-code-highlight")})},XI=function(a){var b=a.getElementsByTagName("pre")[0];if(b){if(b.classList.contains("devsite-disable-click-to-copy")||b.hasAttribute("no-copy")||!b.classList.contains("devsite-click-to-copy")&&!b.classList.contains("prettyprint")&&!b.classList.contains("devsite-terminal"))a.setAttribute("no-copy",""),b.classList.remove("devsite-disable-click-to-copy"),b.removeAttribute("no-copy");a.setAttribute("data-copy-event-label",
b.getAttribute("data-copy-event-label")||"");b.classList.remove("devsite-click-to-copy");b=b.getAttribute("data-label");a.G=b?"Copy code sample: "+b:"Copy code sample"}var c=a.querySelector(".devsite-enable-open-in-jsfiddle,.devsite-jsfiddle-code-sample");c&&(a.setAttribute("js-fiddle",""),c.classList.remove("devsite-enable-open-in-jsfiddle"),c.classList.add("devsite-jsfiddle-code-sample"));a.hasAttribute("js-fiddle")&&c&&["scope","jsfiddle-title","jsfiddle-wrap","jsfiddle-label"].forEach(function(d){c.hasAttribute("data-"+
d)&&(a.setAttribute(d,c.getAttribute("data-"+d)),c.removeAttribute("data-"+d))})},YI=function(a){var b,c;return _ds.E(function(d){if(1==d.h){b=Array.from(a.querySelector("pre:not(.devsite-copy-hide)").childNodes);_ds.Js(document.body,b);if(!a.F)return d.J(0);c=new _ds.zl;a.m.setAttribute("aria-label","Code sample copied to clipboard");_ds.Fj(a.j,a.F,_ds.mv,function(){c.resolve()});return _ds.w(d,c.promise,3)}_ds.Fj(a.j,a.F,_ds.mv,function(){a.m.setAttribute("aria-label",a.G)});_ds.x(d)})},ZI=function(a){a.C&&
a.j.listen(a.C,"click",function(){return void a.setAttribute("dark-code","")});a.D&&a.j.listen(a.D,"click",function(){return void a.removeAttribute("dark-code")});a.m&&a.j.listen(a.m,"click",function(){return void YI(a)});a.o&&a.j.listen(a.o,"click",function(){var b={title:a.getAttribute("jsfiddle-title")||"Code sample",wrap:a.getAttribute("jsfiddle-wrap")||"b",description:""},c=a.getAttribute("scope");c?_ds.Ys(c,b):_ds.Xs([a],b)})};/*
 Copyright (C) 2006 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
window.PR_SHOULD_USE_CONTINUATION=!0;window.PR_TAB_WIDTH=8;window.PR_normalizedHtml=void 0;window.PR=void 0;window.prettyPrintOne=void 0;window.prettyPrint=void 0;window._pr_isIE6=function(){var a=navigator&&navigator.userAgent&&navigator.userAgent.match(/\bMSIE ([678])\./);a=a?+a[1]:!1;window._pr_isIE6=function(){return a};return a};
(function(){function a(aa){return aa.replace(v,"&amp;").replace(y,"&lt;").replace(A,"&gt;")}function b(aa,qa,H){switch(aa.nodeType){case 1:var Da=aa.tagName.toLowerCase();qa.push("<",Da);var Ma=aa.attributes,db=Ma.length;if(db){if(H){for(var Va=[],Na=db;0<=--Na;)Va[Na]=Ma[Na];Va.sort(function(Ia,Ya){return Ia.name<Ya.name?-1:Ia.name===Ya.name?0:1});Ma=Va}for(Na=0;Na<db;++Na)Va=Ma[Na],Va.specified&&qa.push(" ",Va.name.toLowerCase(),'="',Va.value.replace(v,"&amp;").replace(y,"&lt;").replace(A,"&gt;").replace(D,
"&quot;"),'"')}qa.push(">");for(Ma=aa.firstChild;Ma;Ma=Ma.nextSibling)b(Ma,qa,H);!aa.firstChild&&/^(?:br|link|img)$/.test(Da)||qa.push("</",Da,">");break;case 3:case 4:qa.push(a(aa.nodeValue))}}function c(aa){function qa(sa){if("\\"!==sa.charAt(0))return sa.charCodeAt(0);switch(sa.charAt(1)){case "b":return 8;case "t":return 9;case "n":return 10;case "v":return 11;case "f":return 12;case "r":return 13;case "u":case "x":return parseInt(sa.substring(2),16)||sa.charCodeAt(1);case "0":case "1":case "2":case "3":case "4":case "5":case "6":case "7":return parseInt(sa.substring(1),
8);default:return sa.charCodeAt(1)}}function H(sa){if(32>sa)return(16>sa?"\\x0":"\\x")+sa.toString(16);sa=String.fromCharCode(sa);if("\\"===sa||"-"===sa||"["===sa||"]"===sa)sa="\\"+sa;return sa}function Da(sa){var va=sa.substring(1,sa.length-1).match(/\\u[0-9A-Fa-f]{4}|\\x[0-9A-Fa-f]{2}|\\[0-3][0-7]{0,2}|\\[0-7]{1,2}|\\[\s\S]|-|[^-\\]/g);sa=[];for(var ma=[],Qa="^"===va[0],ya=Qa?1:0,Ja=va.length;ya<Ja;++ya){var ea=va[ya];switch(ea){case "\\B":case "\\b":case "\\D":case "\\d":case "\\S":case "\\s":case "\\W":case "\\w":sa.push(ea);
continue}ea=qa(ea);if(ya+2<Ja&&"-"===va[ya+1]){var gb=qa(va[ya+2]);ya+=2}else gb=ea;ma.push([ea,gb]);65>gb||122<ea||(65>gb||90<ea||ma.push([Math.max(65,ea)|32,Math.min(gb,90)|32]),97>gb||122<ea||ma.push([Math.max(97,ea)&-33,Math.min(gb,122)&-33]))}ma.sort(function(fc,Pe){return fc[0]-Pe[0]||Pe[1]-fc[1]});va=[];ea=[NaN,NaN];for(ya=0;ya<ma.length;++ya)Ja=ma[ya],Ja[0]<=ea[1]+1?ea[1]=Math.max(ea[1],Ja[1]):va.push(ea=Ja);ma=["["];Qa&&ma.push("^");ma.push.apply(ma,sa);for(ya=0;ya<va.length;++ya)Ja=va[ya],
ma.push(H(Ja[0])),Ja[1]>Ja[0]&&(Ja[1]+1>Ja[0]&&ma.push("-"),ma.push(H(Ja[1])));ma.push("]");return ma.join("")}function Ma(sa){for(var va=sa.source.match(/(?:\[(?:[^\x5C\x5D]|\\[\s\S])*\]|\\u[A-Fa-f0-9]{4}|\\x[A-Fa-f0-9]{2}|\\[0-9]+|\\[^ux0-9]|\(\?[:!=]|[\(\)\^]|[^\x5B\x5C\(\)\^]+)/g),ma=va.length,Qa=[],ya=0,Ja=0;ya<ma;++ya){var ea=va[ya];"("===ea?++Ja:"\\"===ea.charAt(0)&&(ea=+ea.substring(1))&&ea<=Ja&&(Qa[ea]=-1)}for(ya=1;ya<Qa.length;++ya)-1===Qa[ya]&&(Qa[ya]=++db);for(Ja=ya=0;ya<ma;++ya)ea=va[ya],
"("===ea?(++Ja,void 0===Qa[Ja]&&(va[ya]="(?:")):"\\"===ea.charAt(0)&&(ea=+ea.substring(1))&&ea<=Ja&&(va[ya]="\\"+Qa[Ja]);for(Ja=ya=0;ya<ma;++ya)"^"===va[ya]&&"^"!==va[ya+1]&&(va[ya]="");if(sa.ignoreCase&&Va)for(ya=0;ya<ma;++ya)ea=va[ya],sa=ea.charAt(0),2<=ea.length&&"["===sa?va[ya]=Da(ea):"\\"!==sa&&(va[ya]=ea.replace(/[a-zA-Z]/g,function(gb){gb=gb.charCodeAt(0);return"["+String.fromCharCode(gb&-33,gb|32)+"]"}));return va.join("")}for(var db=0,Va=!1,Na=!1,Ia=0,Ya=aa.length;Ia<Ya;++Ia){var Wa=aa[Ia];
if(Wa.ignoreCase)Na=!0;else if(/[a-z]/i.test(Wa.source.replace(/\\u[0-9a-f]{4}|\\x[0-9a-f]{2}|\\[^ux]/gi,""))){Va=!0;Na=!1;break}}var Sa=[];Ia=0;for(Ya=aa.length;Ia<Ya;++Ia){Wa=aa[Ia];if(Wa.global||Wa.multiline)throw Error(""+Wa);Sa.push("(?:"+Ma(Wa)+")")}return new RegExp(Sa.join("|"),Na?"gi":"g")}function d(aa){var qa=0;return function(H){for(var Da=null,Ma=0,db=0,Va=H.length;db<Va;++db)switch(H.charAt(db)){case "\t":Da||(Da=[]);Da.push(H.substring(Ma,db));Ma=aa-qa%aa;for(qa+=Ma;0<=Ma;Ma-=16)Da.push("                ".substring(0,
Ma));Ma=db+1;break;case "\n":qa=0;break;default:++qa}if(!Da)return H;Da.push(H.substring(Ma));return Da.join("")}}function e(aa,qa,H,Da){qa&&(aa={source:qa,hh:aa},H(aa),Da.push.apply(Da,aa.Bh))}function g(aa,qa){function H(Va){for(var Na=Va.hh,Ia=[Na,"pln"],Ya=0,Wa=Va.source.match(Ma)||[],Sa={},sa=0,va=Wa.length;sa<va;++sa){var ma=Wa[sa],Qa=Sa[ma],ya=void 0;if("string"===typeof Qa)var Ja=!1;else{var ea=Da[ma.charAt(0)];if(ea)ya=ma.match(ea[1]),Qa=ea[0];else{for(Ja=0;Ja<db;++Ja)if(ea=qa[Ja],ya=ma.match(ea[1])){Qa=
ea[0];break}ya||(Qa="pln")}!(Ja=5<=Qa.length&&"lang-"===Qa.substring(0,5))||ya&&"string"===typeof ya[1]||(Ja=!1,Qa="src");Ja||(Sa[ma]=Qa)}ea=Ya;Ya+=ma.length;if(Ja){Ja=ya[1];var gb=ma.indexOf(Ja),fc=gb+Ja.length;ya[2]&&(fc=ma.length-ya[2].length,gb=fc-Ja.length);Qa=Qa.substring(5);e(Na+ea,ma.substring(0,gb),H,Ia);e(Na+ea+gb,Ja,q(Qa,Ja),Ia);e(Na+ea+fc,ma.substring(fc),H,Ia)}else Ia.push(Na+ea,Qa)}Va.Bh=Ia}var Da={},Ma;(function(){for(var Va=aa.concat(qa),Na=[],Ia={},Ya=0,Wa=Va.length;Ya<Wa;++Ya){var Sa=
Va[Ya],sa=Sa[3];if(sa)for(var va=sa.length;0<=--va;)Da[sa.charAt(va)]=Sa;Sa=Sa[1];sa=""+Sa;Ia.hasOwnProperty(sa)||(Na.push(Sa),Ia[sa]=null)}Na.push(/[\0-\uffff]/);Ma=c(Na)})();var db=qa.length;return H}function k(aa){var qa=[],H=[];aa.tripleQuotedStrings?qa.push(["str",/^(?:'''(?:[^'\\]|\\[\s\S]|'{1,2}(?=[^']))*(?:'''|$)|"""(?:[^"\\]|\\[\s\S]|"{1,2}(?=[^"]))*(?:"""|$)|'(?:[^\\']|\\[\s\S])*(?:'|$)|"(?:[^\\"]|\\[\s\S])*(?:"|$))/,null,"'\""]):aa.multiLineStrings?qa.push(["str",/^(?:'(?:[^\\']|\\[\s\S])*(?:'|$)|"(?:[^\\"]|\\[\s\S])*(?:"|$)|`(?:[^\\`]|\\[\s\S])*(?:`|$))/,
null,"'\"`"]):qa.push(["str",/^(?:'(?:[^\\'\r\n]|\\.)*(?:'|$)|"(?:[^\\"\r\n]|\\.)*(?:"|$))/,null,"\"'"]);aa.verbatimStrings&&H.push(["str",/^@"(?:[^"]|"")*(?:"|$)/,null]);var Da=aa.hashComments;Da&&(aa.cStyleComments?(1<Da?qa.push(["com",/^#(?:##(?:[^#]|#(?!##))*(?:###|$)|.*)/,null,"#"]):qa.push(["com",/^#(?:(?:define|elif|else|endif|error|ifdef|include|ifndef|line|pragma|undef|warning)\b|[^\r\n]*)/,null,"#"]),H.push(["str",/^<(?:(?:(?:\.\.\/)*|\/?)(?:[\w-]+(?:\/[\w-]+)+)?[\w-]+\.h|[a-z]\w*)>/,null])):
qa.push(["com",/^#[^\r\n]*/,null,"#"]));aa.cStyleComments&&(H.push(["com",/^\/\/[^\r\n]*/,null]),H.push(["com",/^\/\*[\s\S]*?(?:\*\/|$)/,null]));aa.regexLiterals&&H.push(["lang-regex",new RegExp("^"+t+"(/(?=[^/*])(?:[^/\\x5B\\x5C]|\\x5C[\\s\\S]|\\x5B(?:[^\\x5C\\x5D]|\\x5C[\\s\\S])*(?:\\x5D|$))+/)")]);aa=aa.keywords.replace(/^\s+|\s+$/g,"");aa.length&&H.push(["kwd",new RegExp("^(?:"+aa.replace(/\s+/g,"|")+")\\b"),null]);qa.push(["pln",/^\s+/,null," \r\n\t\u00a0"]);H.push(["lit",/^@[a-z_$][a-z_$@0-9]*/i,
null],["typ",/^@?[A-Z]+[a-z][A-Za-z_$@0-9]*/,null],["pln",/^[a-z_$][a-z_$@0-9]*/i,null],["lit",/^(?:0x[a-f0-9]+|(?:\d(?:_\d+)*\d*(?:\.\d*)?|\.\d\+)(?:e[+\-]?\d+)?)[a-z]*/i,null,"0123456789"],["pun",/^.[^\s\w\.$@'"`\/#]*/,null]);return g(qa,H)}function m(aa){function qa(Qe){if(Qe>Ia){Ya&&Ya!==Wa&&(Na.push("</span>"),Ya=null);!Ya&&Wa&&(Ya=Wa,Na.push('<span class="',Ya,'">'));var co=a(va(H.substring(Ia,Qe))).replace(ea?Qa:ma,"$1&#160;");ea=Ja.test(co);Na.push(co.replace(ya,eo));Ia=Qe}}var H=aa.source,
Da=aa.Rl,Ma=aa.Bh,db=aa.Gi,Va=aa.Fj,Na=[],Ia=0,Ya=null,Wa=null,Sa=0,sa=0,va=d(window.PR_TAB_WIDTH),ma=/([\r\n ]) /g,Qa=/(^| ) /gm,ya=/\r\n?|\n/g,Ja=/[ \r\n]$/,ea=!0,gb=window._pr_isIE6();Va=gb?Va&&"PRE"===Va.tagName?6===gb?"&#160;\r\n":7===gb?"&#160;<br />\r":8===gb?"&#160;<br />":"&#160;\r":"&#160;<br />":"<br />";if(db){var fc=[];for(gb=0;10>gb;++gb)fc[gb]=Va+'</li><li class="L'+gb+'">';var Pe="number"===typeof db?db-1:0;Na.push('<ol class="linenums"><li class="L',Pe%10,'"');Pe&&Na.push(' value="',
Pe+1,'"');Na.push(">");var eo=function(){var Qe=fc[++Pe%10];return Ya?"</span>"+Qe+'<span class="'+Ya+'">':Qe}}else eo=Va;for(;;)if(Sa<Da.length&&(sa<Ma.length?Da[Sa]<=Ma[sa]:1))qa(Da[Sa]),Ya&&(Na.push("</span>"),Ya=null),Na.push(Da[Sa+1]),Sa+=2;else if(sa<Ma.length)qa(Ma[sa]),Wa=Ma[sa+1],sa+=2;else break;qa(H.length);Ya&&Na.push("</span>");db&&Na.push("</li></ol>");aa.Wf=Na.join("")}function n(aa,qa){for(var H=qa.length;0<=--H;){var Da=qa[H];cb.hasOwnProperty(Da)?"console"in window&&console.warn("cannot override language handler %s",
Da):cb[Da]=aa}}function q(aa,qa){aa&&cb.hasOwnProperty(aa)||(aa=/^\s*</.test(qa)?"default-markup":"default-code");return cb[aa]}function r(aa){var qa=aa.Ej,H=aa.gi;aa.Wf=qa;try{var Da=qa.match(Ra);qa=[];var Ma=0,db=[];if(Da)for(var Va=0,Na=Da.length;Va<Na;++Va){var Ia=Da[Va];if(1<Ia.length&&"<"===Ia.charAt(0)){if(!na.test(Ia))if(nb.test(Ia))qa.push(Ia.substring(9,Ia.length-3)),Ma+=Ia.length-12;else if(eb.test(Ia))qa.push("\n"),++Ma;else if(0<=Ia.indexOf("nocode")&&Ia.replace(/\s(\w+)\s*=\s*(?:"([^"]*)"|'([^']*)'|(\S+))/g,
' $1="$2$3$4"').match(/[cC][lL][aA][sS][sS]="[^"]*\bnocode\b/)){var Ya=Ia.match(Lb)[2],Wa=1;var Sa=Va+1;a:for(;Sa<Na;++Sa){var sa=Da[Sa].match(Lb);if(sa&&sa[2]===Ya)if("/"===sa[1]){if(0===--Wa)break a}else++Wa}Sa<Na?(db.push(Ma,Da.slice(Va,Sa+1).join("")),Va=Sa):db.push(Ma,Ia)}else db.push(Ma,Ia)}else{Wa=Ia;var va=Wa.indexOf("&");if(0>va)var ma=Wa;else{for(--va;0<=(va=Wa.indexOf("&#",va+1));){var Qa=Wa.indexOf(";",va);if(0<=Qa){var ya=Wa.substring(va+3,Qa),Ja=10;ya&&"x"===ya.charAt(0)&&(ya=ya.substring(1),
Ja=16);var ea=parseInt(ya,Ja);isNaN(ea)||(Wa=Wa.substring(0,va)+String.fromCharCode(ea)+Wa.substring(Qa+1))}}ma=Wa.replace(K,"<").replace(X,">").replace(Q,"'").replace(fa,'"').replace(ab," ").replace(la,"&")}qa.push(ma);Ma+=ma.length}}var gb=qa.join("");aa.source=gb;aa.hh=0;aa.Rl=db;q(H,gb)(aa);m(aa)}catch(fc){"console"in window&&console.log(fc&&fc.stack?fc.stack:fc)}}var t=function(){for(var aa="! != !== # % %= & && &&= &= ( * *= += , -= -> / /= : :: ; < << <<= <= = == === > >= >> >>= >>> >>>= ? @ [ ^ ^= ^^ ^^= { | |= || ||= ~ break case continue delete do else finally instanceof return throw try typeof".split(" "),
qa="(?:^^|[+-]",H=0;H<aa.length;++H)qa+="|"+aa[H].replace(/([^=<>:&a-z])/g,"\\$1");return qa+")\\s*"}(),v=/&/g,y=/</g,A=/>/g,D=/"/g,K=/&lt;/g,X=/&gt;/g,Q=/&apos;/g,fa=/&quot;/g,la=/&amp;/g,ab=/&nbsp;/g,Pa=/[\r\n]/g,ra=null,Ra=/[^<]+|\x3c!--[\s\S]*?--\x3e|<!\[CDATA\[[\s\S]*?\]\]>|<\/?[a-zA-Z](?:[^>"']|'[^']*'|"[^"]*")*>|</g,na=/^\x3c!--/,nb=/^<!\[CDATA\[/,eb=/^<br\b/i,Lb=/^<(\/?)([a-zA-Z][a-zA-Z0-9]*)/,ec=k({keywords:"break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof alignof align_union asm axiom bool concept concept_map const_cast constexpr decltype dynamic_cast explicit export friend inline late_check mutable namespace nullptr reinterpret_cast static_assert static_cast template typeid typename using virtual wchar_t where break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof abstract boolean byte extends final finally implements import instanceof null native package strictfp super synchronized throws transient as base by checked decimal delegate descending dynamic event fixed foreach from group implicit in interface internal into is lock object out override orderby params partial readonly ref sbyte sealed stackalloc string select uint ulong unchecked unsafe ushort var break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof debugger eval export function get null set undefined var with Infinity NaN caller delete die do dump elsif eval exit foreach for goto if import last local my next no our print package redo require sub undef unless until use wantarray while BEGIN END break continue do else for if return while and as assert class def del elif except exec finally from global import in is lambda nonlocal not or pass print raise try with yield False True None break continue do else for if return while alias and begin case class def defined elsif end ensure false in module next nil not or redo rescue retry self super then true undef unless until when yield BEGIN END break continue do else for if return while case done elif esac eval fi function in local set then until ",
hashComments:!0,cStyleComments:!0,multiLineStrings:!0,regexLiterals:!0}),cb={};n(ec,["default-code"]);n(g([],[["pln",/^[^<?]+/],["dec",/^<!\w[^>]*(?:>|$)/],["com",/^\x3c!--[\s\S]*?(?:-\->|$)/],["lang-",/^<\?([\s\S]+?)(?:\?>|$)/],["lang-",/^<%([\s\S]+?)(?:%>|$)/],["pun",/^(?:<[%?]|[%?]>)/],["lang-",/^<xmp\b[^>]*>([\s\S]+?)<\/xmp\b[^>]*>/i],["lang-js",/^<script\b[^>]*>([\s\S]*?)(<\/script\b[^>]*>)/i],["lang-css",/^<style\b[^>]*>([\s\S]*?)(<\/style\b[^>]*>)/i],["lang-in.tag",/^(<\/?[a-z][^<>]*>)/i]]),
"default-markup htm html mxml xhtml xml xsl".split(" "));n(g([["pln",/^[\s]+/,null," \t\r\n"],["atv",/^(?:"[^"]*"?|'[^']*'?)/,null,"\"'"]],[["tag",/^^<\/?[a-z](?:[\w.:-]*\w)?|\/?>$/i],["atn",/^(?!style[\s=]|on)[a-z](?:[\w:-]*\w)?/i],["lang-uq.val",/^=\s*([^>'"\s]*(?:[^>'"\s\/]|\/(?=\s)))/],["pun",/^[=<>\/]+/],["lang-js",/^on\w+\s*=\s*"([^"]+)"/i],["lang-js",/^on\w+\s*=\s*'([^']+)'/i],["lang-js",/^on\w+\s*=\s*([^"'>\s]+)/i],["lang-css",/^style\s*=\s*"([^"]+)"/i],["lang-css",/^style\s*=\s*'([^']+)'/i],
["lang-css",/^style\s*=\s*([^"'>\s]+)/i]]),["in.tag"]);n(g([],[["atv",/^[\s\S]+/]]),["uq.val"]);n(k({keywords:"break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof alignof align_union asm axiom bool concept concept_map const_cast constexpr decltype dynamic_cast explicit export friend inline late_check mutable namespace nullptr reinterpret_cast static_assert static_cast template typeid typename using virtual wchar_t where ",
hashComments:!0,cStyleComments:!0}),"c cc cpp cxx cyc m".split(" "));n(k({keywords:"null true false"}),["json"]);n(k({keywords:"break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof abstract boolean byte extends final finally implements import instanceof null native package strictfp super synchronized throws transient as base by checked decimal delegate descending dynamic event fixed foreach from group implicit in interface internal into is lock object out override orderby params partial readonly ref sbyte sealed stackalloc string select uint ulong unchecked unsafe ushort var ",
hashComments:!0,cStyleComments:!0,verbatimStrings:!0}),["cs"]);n(k({keywords:"break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof abstract boolean byte extends final finally implements import instanceof null native package strictfp super synchronized throws transient ",
cStyleComments:!0}),["java"]);n(k({keywords:"break continue do else for if return while case done elif esac eval fi function in local set then until ",hashComments:!0,multiLineStrings:!0}),["bsh","csh","sh"]);n(k({keywords:"break continue do else for if return while and as assert class def del elif except exec finally from global import in is lambda nonlocal not or pass print raise try with yield False True None ",hashComments:!0,multiLineStrings:!0,tripleQuotedStrings:!0}),["cv","py"]);n(k({keywords:"caller delete die do dump elsif eval exit foreach for goto if import last local my next no our print package redo require sub undef unless until use wantarray while BEGIN END ",
hashComments:!0,multiLineStrings:!0,regexLiterals:!0}),["perl","pl","pm"]);n(k({keywords:"break continue do else for if return while alias and begin case class def defined elsif end ensure false in module next nil not or redo rescue retry self super then true undef unless until when yield BEGIN END ",hashComments:!0,multiLineStrings:!0,regexLiterals:!0}),["rb"]);n(k({keywords:"break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof debugger eval export function get null set undefined var with Infinity NaN ",
cStyleComments:!0,regexLiterals:!0}),["js"]);n(k({keywords:"all and by catch class else extends false finally for if in is isnt loop new no not null of off on or return super then true try unless until when while yes ",hashComments:3,cStyleComments:!0,multilineStrings:!0,tripleQuotedStrings:!0,regexLiterals:!0}),["coffee"]);n(g([],[["str",/^[\s\S]+/]]),["regex"]);window.PR_normalizedHtml=b;window.prettyPrintOne=function(aa,qa,H){aa={Ej:aa,gi:qa,Gi:H};r(aa);return aa.Wf};window.prettyPrint=function(aa){function qa(){for(var Wa=
window.PR_SHOULD_USE_CONTINUATION?Na.now()+250:Infinity;Ia<Da.length&&Na.now()<Wa;Ia++){var Sa=Da[Ia];if(Sa.className&&0<=Sa.className.indexOf("prettyprint")){var sa=Sa.className.match(/\blang-(\w+)\b/);sa&&(sa=sa[1]);for(var va=!1,ma=Sa.parentNode;ma;ma=ma.parentNode)if(("pre"===ma.tagName||"code"===ma.tagName||"xmp"===ma.tagName)&&ma.className&&0<=ma.className.indexOf("prettyprint")){va=!0;break}if(!va){ma=Sa;null===ra&&(va=document.createElement("PRE"),va.appendChild(document.createTextNode('<!DOCTYPE foo PUBLIC "foo bar">\n<foo />')),
ra=!/</.test(va.innerHTML));if(ra)if(va=ma.innerHTML,"XMP"===ma.tagName)va=a(va);else{if("PRE"!==ma.tagName&&Pa.test(va)){var Qa="";ma.currentStyle?Qa=ma.currentStyle.whiteSpace:window.getComputedStyle&&(Qa=window.getComputedStyle(ma,null).whiteSpace);ma=!Qa||"pre"===Qa}else ma=!0;ma||(va=va.replace(/(<br\s*\/?>)[\r\n]+/g,"$1").replace(/(?:[\r\n]+[ \t]*)+/g," "))}else{va=[];for(ma=ma.firstChild;ma;ma=ma.nextSibling)b(ma,va);va=va.join("")}va=va.replace(/(?:\r\n?|\n)$/,"");ma=Sa.className.match(/\blinenums\b(?::(\d+))?/);
Ya={Ej:va,gi:sa,Fj:Sa,Gi:ma?ma[1]&&ma[1].length?+ma[1]:!0:!1};r(Ya);if(Sa=Ya.Wf)if(sa=Ya.Fj,"XMP"===sa.tagName){va=document.createElement("PRE");for(ma=0;ma<sa.attributes.length;++ma)Qa=sa.attributes[ma],Qa.specified&&("class"===Qa.name.toLowerCase()?va.className=Qa.value:va.setAttribute(Qa.name,Qa.value));va.innerHTML=Sa;sa.parentNode.replaceChild(va,sa)}else sa.innerHTML=Sa}}}Ia<Da.length?setTimeout(qa,250):aa&&aa()}for(var H=[document.getElementsByTagName("pre"),document.getElementsByTagName("code"),
document.getElementsByTagName("xmp")],Da=[],Ma=0;Ma<H.length;++Ma)for(var db=0,Va=H[Ma].length;db<Va;++db)Da.push(H[Ma][db]);H=null;var Na=Date;Na.now||(Na={now:function(){return(new Date).getTime()}});var Ia=0,Ya;qa()};window.PR={combinePrefixPatterns:c,createSimpleLexer:g,registerLangHandler:n,sourceDecorator:k,PR_ATTRIB_NAME:"atn",PR_ATTRIB_VALUE:"atv",PR_COMMENT:"com",PR_DECLARATION:"dec",PR_KEYWORD:"kwd",PR_LITERAL:"lit",PR_NOCODE:"nocode",PR_PLAIN:"pln",PR_PUNCTUATION:"pun",PR_SOURCE:"src",
PR_STRING:"str",PR_TAG:"tag",PR_TYPE:"typ"}})();/*
 Copyright (C) 2009 Onno Hommes.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_COMMENT,/^#[^\r\n]*/,null,"#"],[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_STRING,/^"(?:[^"\\]|\\[\s\S])*(?:"|$)/,null,'"']],[[PR.PR_KEYWORD,/^(?:ADS|AD|AUG|BZF|BZMF|CAE|CAF|CA|CCS|COM|CS|DAS|DCA|DCOM|DCS|DDOUBL|DIM|DOUBLE|DTCB|DTCF|DV|DXCH|EDRUPT|EXTEND|INCR|INDEX|NDX|INHINT|LXCH|MASK|MSK|MP|MSU|NOOP|OVSK|QXCH|RAND|READ|RELINT|RESUME|RETURN|ROR|RXOR|SQUARE|SU|TCR|TCAA|OVSK|TCF|TC|TS|WAND|WOR|WRITE|XCH|XLQ|XXALQ|ZL|ZQ|ADD|ADZ|SUB|SUZ|MPY|MPR|MPZ|DVP|COM|ABS|CLA|CLZ|LDQ|STO|STQ|ALS|LLS|LRS|TRA|TSQ|TMI|TOV|AXT|TIX|DLY|INP|OUT)\s/,
null],[PR.PR_TYPE,/^(?:-?GENADR|=MINUS|2BCADR|VN|BOF|MM|-?2CADR|-?[1-6]DNADR|ADRES|BBCON|[SE]?BANK=?|BLOCK|BNKSUM|E?CADR|COUNT\*?|2?DEC\*?|-?DNCHAN|-?DNPTR|EQUALS|ERASE|MEMORY|2?OCT|REMADR|SETLOC|SUBRO|ORG|BSS|BES|SYN|EQU|DEFINE|END)\s/,null],[PR.PR_LITERAL,/^'(?:-*(?:\w|\\[\x21-\x7e])(?:[\w-]*|\\[\x21-\x7e])[=!?]?)?/],[PR.PR_PLAIN,/^-*(?:[!-z_]|\\[\x21-\x7e])(?:[\w-]*|\\[\x21-\x7e])[=!?]?/i],[PR.PR_PUNCTUATION,/^[^\w\t\n\r \xA0()"\\';]+/]]),["apollo","agc","aea"]);/*
 Copyright (C) 2011 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
PR.registerLangHandler(PR.createSimpleLexer([["opn",/^[\(\{\[]+/,null,"([{"],["clo",/^[\)\}\]]+/,null,")]}"],[PR.PR_COMMENT,/^;[^\r\n]*/,null,";"],[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_STRING,/^"(?:[^"\\]|\\[\s\S])*(?:"|$)/,null,'"']],[[PR.PR_KEYWORD,/^(?:def|if|do|let|quote|var|fn|loop|recur|throw|try|monitor-enter|monitor-exit|defmacro|defn|defn-|macroexpand|macroexpand-1|for|doseq|dosync|dotimes|and|or|when|not|assert|doto|proxy|defstruct|first|rest|cons|defprotocol|deftype|defrecord|reify|defmulti|defmethod|meta|with-meta|ns|in-ns|create-ns|import|intern|refer|alias|namespace|resolve|ref|deref|refset|new|set!|memfn|to-array|into-array|aset|gen-class|reduce|map|filter|find|nil?|empty?|hash-map|hash-set|vec|vector|seq|flatten|reverse|assoc|dissoc|list|list?|disj|get|union|difference|intersection|extend|extend-type|extend-protocol|prn)\b/,
null],[PR.PR_TYPE,/^:[0-9a-zA-Z\-]+/]]),["clj"]);/*
 Copyright (C) 2009 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[ \t\r\n\f]+/,null," \t\r\n\f"]],[[PR.PR_STRING,/^"(?:[^\n\r\f\\"]|\\(?:\r\n?|\n|\f)|\\[\s\S])*"/,null],[PR.PR_STRING,/^'(?:[^\n\r\f\\']|\\(?:\r\n?|\n|\f)|\\[\s\S])*'/,null],["lang-css-str",/^url\(([^\)"']*)\)/i],[PR.PR_KEYWORD,/^(?:url|rgb|!important|@import|@page|@media|@charset|inherit)(?=[^\-\w]|$)/i,null],["lang-css-kw",/^(-?(?:[_a-z]|(?:\\[0-9a-f]+ ?))(?:[_a-z0-9\-]|\\(?:\\[0-9a-f]+ ?))*)\s*:/i],[PR.PR_COMMENT,/^\/\*[^*]*\*+(?:[^\/*][^*]*\*+)*\//],
[PR.PR_COMMENT,/^(?:\x3c!--|--\x3e)/],[PR.PR_LITERAL,/^(?:\d+|\d*\.\d+)(?:%|[a-z]+)?/i],[PR.PR_LITERAL,/^#(?:[0-9a-f]{3}){1,2}/i],[PR.PR_PLAIN,/^-?(?:[_a-z]|(?:\\[\da-f]+ ?))(?:[_a-z\d\-]|\\(?:\\[\da-f]+ ?))*/i],[PR.PR_PUNCTUATION,/^[^\s\w'"]+/]]),["css"]);PR.registerLangHandler(PR.createSimpleLexer([],[[PR.PR_KEYWORD,/^-?(?:[_a-z]|(?:\\[\da-f]+ ?))(?:[_a-z\d\-]|\\(?:\\[\da-f]+ ?))*/i]]),["css-kw"]);PR.registerLangHandler(PR.createSimpleLexer([],[[PR.PR_STRING,/^[^\)"']+/]]),["css-str"]);/*
 Copyright (C) 2010 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_PLAIN,/^(?:"(?:[^"\\]|\\[\s\S])*(?:"|$)|'(?:[^'\\]|\\[\s\S])+(?:'|$))/,null,"\"'"]],[[PR.PR_COMMENT,/^(?:\/\/[^\r\n]*|\/\*[\s\S]*?\*\/)/],[PR.PR_PLAIN,/^(?:[^\/"']|\/(?![\/\*]))+/i]]),["go"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\x0B\x0C\r ]+/,null,"\t\n\x0B\f\r "],[PR.PR_STRING,/^"(?:[^"\\\n\x0C\r]|\\[\s\S])*(?:"|$)/,null,'"'],[PR.PR_STRING,/^'(?:[^'\\\n\x0C\r]|\\[^&])'?/,null,"'"],[PR.PR_LITERAL,/^(?:0o[0-7]+|0x[\da-f]+|\d+(?:\.\d+)?(?:e[+\-]?\d+)?)/i,null,"0123456789"]],[[PR.PR_COMMENT,/^(?:(?:--+(?:[^\r\n\x0C]*)?)|(?:\{-(?:[^-]|-+[^-\}])*-\}))/],[PR.PR_KEYWORD,/^(?:case|class|data|default|deriving|do|else|if|import|in|infix|infixl|infixr|instance|let|module|newtype|of|then|type|where|_)(?=[^a-zA-Z0-9']|$)/,
null],[PR.PR_PLAIN,/^(?:[A-Z][\w']*\.)*[a-zA-Z][\w']*/],[PR.PR_PUNCTUATION,/^[^\t\n\x0B\x0C\r a-zA-Z0-9'"]+/]]),["hs"]);/*

 Copyright (C) 2017 Micha? B?czkowski

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_PUNCTUATION,/^[.!%&()*+,\-;<=>?\[\\\]^{|}:]+/,null,".!%&()*+,-;<=>?[\\]^{|}:"]],[[PR.PR_KEYWORD,/^\b(package|public|protected|private|open|abstract|constructor|final|override|import|for|while|as|typealias|get|set|((data|enum|annotation|sealed) )?class|this|super|val|var|fun|is|in|throw|return|break|continue|(companion )?object|if|try|else|do|when|init|interface|typeof|suspend)\b/],[PR.PR_LITERAL,
/^(?:true|false|null)\b/],[PR.PR_LITERAL,/^(0[xX][0-9a-fA-F_]+L?|0[bB][0-1]+L?|[0-9_.]+([eE]-?[0-9]+)?[fFL]?)/],[PR.PR_TYPE,/^(\b[A-Z]+[a-z][a-zA-Z0-9_$@]*|`.*`)/,null],[PR.PR_COMMENT,/^\/\/.*/],[PR.PR_COMMENT,/^\/\*[\s\S]*?(?:\*\/|$)/],[PR.PR_STRING,/'.'/],[PR.PR_STRING,/^"([^"\\]|\\[\s\S])*"/],[PR.PR_STRING,/^"{3}[\s\S]*?[^\\]"{3}/],[PR.PR_LITERAL,/^@([a-zA-Z0-9_$@]*|`.*`)/],[PR.PR_LITERAL,/^[a-zA-Z0-9_]+@/]]),["kotlin"]);/*
 Copyright (C) 2008 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
PR.registerLangHandler(PR.createSimpleLexer([["opn",/^\(+/,null,"("],["clo",/^\)+/,null,")"],[PR.PR_COMMENT,/^;[^\r\n]*/,null,";"],[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_STRING,/^"(?:[^"\\]|\\[\s\S])*(?:"|$)/,null,'"']],[[PR.PR_KEYWORD,/^(?:block|c[ad]+r|catch|con[ds]|def(?:ine|un)|do|eq|eql|equal|equalp|eval-when|flet|format|go|if|labels|lambda|let|load-time-value|locally|macrolet|multiple-value-call|nil|progn|progv|quote|require|return-from|setq|symbol-macrolet|t|tagbody|the|throw|unwind)\b/,
null],[PR.PR_LITERAL,/^[+\-]?(?:[0#]x[0-9a-f]+|\d+\/\d+|(?:\.\d+|\d+(?:\.\d*)?)(?:[ed][+\-]?\d+)?)/i],[PR.PR_LITERAL,/^'(?:-*(?:\w|\\[\x21-\x7e])(?:[\w-]*|\\[\x21-\x7e])[=!?]?)?/],[PR.PR_PLAIN,/^-*(?:[a-z_]|\\[\x21-\x7e])(?:[\w-]*|\\[\x21-\x7e])[=!?]?/i],[PR.PR_PUNCTUATION,/^[^\w\t\n\r \xA0()"\\';]+/]]),["cl","el","lisp","scm"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_STRING,/^(?:"(?:[^"\\]|\\[\s\S])*(?:"|$)|'(?:[^'\\]|\\[\s\S])*(?:'|$))/,null,"\"'"]],[[PR.PR_COMMENT,/^--(?:\[(=*)\[[\s\S]*?(?:\]\1\]|$)|[^\r\n]*)/],[PR.PR_STRING,/^\[(=*)\[[\s\S]*?(?:\]\1\]|$)/],[PR.PR_KEYWORD,/^(?:and|break|do|else|elseif|end|false|for|function|if|in|local|nil|not|or|repeat|return|then|true|until|while)\b/,null],[PR.PR_LITERAL,/^[+-]?(?:0x[\da-f]+|(?:(?:\.\d+|\d+(?:\.\d*)?)(?:e[+\-]?\d+)?))/i],
[PR.PR_PLAIN,/^[a-z_]\w*/i],[PR.PR_PUNCTUATION,/^[^\w\t\n\r \xA0][^\w\t\n\r \xA0"'\-\+=]*/]]),["lua"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_COMMENT,/^#(?:if[\t\n\r \xA0]+(?:[a-z_$][\w']*|``[^\r\n\t`]*(?:``|$))|else|endif|light)/i,null,"#"],[PR.PR_STRING,/^(?:"(?:[^"\\]|\\[\s\S])*(?:"|$)|'(?:[^'\\]|\\[\s\S])(?:'|$))/,null,"\"'"]],[[PR.PR_COMMENT,/^(?:\/\/[^\r\n]*|\(\*[\s\S]*?\*\))/],[PR.PR_KEYWORD,/^(?:abstract|and|as|assert|begin|class|default|delegate|do|done|downcast|downto|elif|else|end|exception|extern|false|finally|for|fun|function|if|in|inherit|inline|interface|internal|lazy|let|match|member|module|mutable|namespace|new|null|of|open|or|override|private|public|rec|return|static|struct|then|to|true|try|type|upcast|use|val|void|when|while|with|yield|asr|land|lor|lsl|lsr|lxor|mod|sig|atomic|break|checked|component|const|constraint|constructor|continue|eager|event|external|fixed|functor|global|include|method|mixin|object|parallel|process|protected|pure|sealed|trait|virtual|volatile)\b/],
[PR.PR_LITERAL,/^[+\-]?(?:0x[\da-f]+|(?:(?:\.\d+|\d+(?:\.\d*)?)(?:e[+\-]?\d+)?))/i],[PR.PR_PLAIN,/^(?:[a-z_][\w']*[!?#]?|``[^\r\n\t`]*(?:``|$))/i],[PR.PR_PUNCTUATION,/^[^\t\n\r \xA0"'\w]+/]]),["fs","ml"]);PR.registerLangHandler(PR.sourceDecorator({keywords:"bool bytes default double enum extend extensions false fixed32 fixed64 float group import int32 int64 max message option optional package repeated required returns rpc service sfixed32 sfixed64 sint32 sint64 string syntax to true uint32 uint64",cStyleComments:!0}),["proto"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_STRING,/^(?:"(?:(?:""(?:""?(?!")|[^\\"]|\\.)*"{0,3})|(?:[^"\r\n\\]|\\.)*"?))/,null,'"'],[PR.PR_LITERAL,/^`(?:[^\r\n\\`]|\\.)*`?/,null,"`"],[PR.PR_PUNCTUATION,/^[!#%&()*+,\-:;<=>?@\[\\\]^{|}~]+/,null,"!#%&()*+,-:;<=>?@[\\]^{|}~"]],[[PR.PR_STRING,/^'(?:[^\r\n\\']|\\(?:'|[^\r\n']+))'/],[PR.PR_LITERAL,/^'[a-zA-Z_$][\w$]*(?!['$\w])/],[PR.PR_KEYWORD,/^(?:abstract|case|catch|class|def|do|else|extends|final|finally|for|forSome|if|implicit|import|lazy|match|new|object|override|package|private|protected|requires|return|sealed|super|throw|trait|try|type|val|var|while|with|yield)\b/],
[PR.PR_LITERAL,/^(?:true|false|null|this)\b/],[PR.PR_LITERAL,/^(?:(?:0(?:[0-7]+|X[0-9A-F]+))L?|(?:(?:0|[1-9][0-9]*)(?:(?:\.[0-9]+)?(?:E[+\-]?[0-9]+)?F?|L?))|\\.[0-9]+(?:E[+\-]?[0-9]+)?F?)/i],[PR.PR_TYPE,/^[$_]*[A-Z][_$A-Z0-9]*[a-z][\w$]*/],[PR.PR_PLAIN,/^[$a-zA-Z_][\w$]*/],[PR.PR_COMMENT,/^\/(?:\/.*|\*(?:\/|\**[^*/])*(?:\*+\/?)?)/],[PR.PR_PUNCTUATION,/^(?:\.+|\/)/]]),["scala"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_STRING,/^(?:"(?:[^"\\]|\\.)*"|'(?:[^'\\]|\\.)*')/,null,"\"'"]],[[PR.PR_COMMENT,/^(?:--[^\r\n]*|\/\*[\s\S]*?(?:\*\/|$))/],[PR.PR_KEYWORD,/^(?:ADD|ALL|ALTER|AND|ANY|AS|ASC|AUTHORIZATION|BACKUP|BEGIN|BETWEEN|BREAK|BROWSE|BULK|BY|CASCADE|CASE|CHECK|CHECKPOINT|CLOSE|CLUSTERED|COALESCE|COLLATE|COLUMN|COMMIT|COMPUTE|CONSTRAINT|CONTAINS|CONTAINSTABLE|CONTINUE|CONVERT|CREATE|CROSS|CURRENT|CURRENT_DATE|CURRENT_TIME|CURRENT_TIMESTAMP|CURRENT_USER|CURSOR|DATABASE|DBCC|DEALLOCATE|DECLARE|DEFAULT|DELETE|DENY|DESC|DISK|DISTINCT|DISTRIBUTED|DOUBLE|DROP|DUMMY|DUMP|ELSE|END|ERRLVL|ESCAPE|EXCEPT|EXEC|EXECUTE|EXISTS|EXIT|FETCH|FILE|FILLFACTOR|FOR|FOREIGN|FREETEXT|FREETEXTTABLE|FROM|FULL|FUNCTION|GOTO|GRANT|GROUP|HAVING|HOLDLOCK|IDENTITY|IDENTITYCOL|IDENTITY_INSERT|IF|IN|INDEX|INNER|INSERT|INTERSECT|INTO|IS|JOIN|KEY|KILL|LEFT|LIKE|LINENO|LOAD|NATIONAL|NOCHECK|NONCLUSTERED|NOT|NULL|NULLIF|OF|OFF|OFFSETS|ON|OPEN|OPENDATASOURCE|OPENQUERY|OPENROWSET|OPENXML|OPTION|OR|ORDER|OUTER|OVER|PERCENT|PLAN|PRECISION|PRIMARY|PRINT|PROC|PROCEDURE|PUBLIC|RAISERROR|READ|READTEXT|RECONFIGURE|REFERENCES|REPLICATION|RESTORE|RESTRICT|RETURN|REVOKE|RIGHT|ROLLBACK|ROWCOUNT|ROWGUIDCOL|RULE|SAVE|SCHEMA|SELECT|SESSION_USER|SET|SETUSER|SHUTDOWN|SOME|STATISTICS|SYSTEM_USER|TABLE|TEXTSIZE|THEN|TO|TOP|TRAN|TRANSACTION|TRIGGER|TRUNCATE|TSEQUAL|UNION|UNIQUE|UPDATE|UPDATETEXT|USE|USER|VALUES|VARYING|VIEW|WAITFOR|WHEN|WHERE|WHILE|WITH|WRITETEXT)(?=[^\w-]|$)/i,
null],[PR.PR_LITERAL,/^[+-]?(?:0x[\da-f]+|(?:(?:\.\d+|\d+(?:\.\d*)?)(?:e[+\-]?\d+)?))/i],[PR.PR_PLAIN,/^[a-z_][\w-]*/i],[PR.PR_PUNCTUATION,/^[^\w\t\n\r \xA0"'][^\w\t\n\r \xA0+\-"']*/]]),["sql"]);/*
 Copyright (C) 2015 Google Inc.
 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0
 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[ \n\r\t\v\f\0]+/,null," \n\r\t\v\f\x00"],[PR.PR_STRING,/^"(?:[^"\\]|(?:\\.)|(?:\\\((?:[^"\\)]|\\.)*\)))*"/,null,'"']],[[PR.PR_LITERAL,/^(?:(?:0x[\da-fA-F][\da-fA-F_]*\.[\da-fA-F][\da-fA-F_]*[pP]?)|(?:\d[\d_]*\.\d[\d_]*[eE]?))[+-]?\d[\d_]*/,null],[PR.PR_LITERAL,/^-?(?:(?:0(?:(?:b[01][01_]*)|(?:o[0-7][0-7_]*)|(?:x[\da-fA-F][\da-fA-F_]*)))|(?:\d[\d_]*))/,null],[PR.PR_LITERAL,/^(?:true|false|nil)\b/,null],[PR.PR_KEYWORD,/^\b(?:__COLUMN__|__FILE__|__FUNCTION__|__LINE__|associativity|as|break|case|class|continue|convenience|default|deinit|didSet|do|dynamic|dynamicType|else|enum|fallthrough|final|for|func|get|import|infix|init|inout|internal|if|in|is|lazy|left|let|mutating|none|nonmutating|operator|optional|override|postfix|precedence|prefix|private|protocol|Protocol|public|required|return|right|safe|self|set|static|struct|subscript|super|switch|Type|typealias|unowned|unsafe|var|weak|while|willSet)\b/,
null],[PR.PR_COMMENT,/^\/\/.*?[\n\r]/,null],[PR.PR_COMMENT,/^\/\*[\s\S]*?(?:\*\/|$)/,null],[PR.PR_PUNCTUATION,/^<<=|<=|<<|>>=|>=|>>|===|==|\.\.\.|&&=|\.\.<|!==|!=|&=|~=|~|\(|\)|\[|\]|{|}|@|#|;|\.|,|:|\|\|=|\?\?|\|\||&&|&\*|&\+|&-|&=|\+=|-=|\/=|\*=|\^=|%=|\|=|->|`|==|\+\+|--|\/|\+|!|\*|%|<|>|&|\||\^|\?|=|-|_/,null],[PR.PR_TYPE,/^\b(?:[@_]?[A-Z]+[a-z][A-Za-z_$@0-9]*|\w+_t\b)/,null]]),["swift"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\r \xA0\u2028\u2029]+/,null,"\t\n\r \u00a0\u2028\u2029"],[PR.PR_STRING,/^(?:["\u201C\u201D](?:[^"\u201C\u201D]|["\u201C\u201D]{2})(?:["\u201C\u201D]c|$)|["\u201C\u201D](?:[^"\u201C\u201D]|["\u201C\u201D]{2})*(?:["\u201C\u201D]|$))/i,null,'"\u201c\u201d'],[PR.PR_COMMENT,/^['\u2018\u2019][^\r\n\u2028\u2029]*/,null,"'\u2018\u2019"]],[[PR.PR_KEYWORD,/^(?:AddHandler|AddressOf|Alias|And|AndAlso|Ansi|As|Assembly|Auto|Boolean|ByRef|Byte|ByVal|Call|Case|Catch|CBool|CByte|CChar|CDate|CDbl|CDec|Char|CInt|Class|CLng|CObj|Const|CShort|CSng|CStr|CType|Date|Decimal|Declare|Default|Delegate|Dim|DirectCast|Do|Double|Each|Else|ElseIf|End|EndIf|Enum|Erase|Error|Event|Exit|Finally|For|Friend|Function|Get|GetType|GoSub|GoTo|Handles|If|Implements|Imports|In|Inherits|Integer|Interface|Is|Let|Lib|Like|Long|Loop|Me|Mod|Module|MustInherit|MustOverride|MyBase|MyClass|Namespace|New|Next|Not|NotInheritable|NotOverridable|Object|On|Option|Optional|Or|OrElse|Overloads|Overridable|Overrides|ParamArray|Preserve|Private|Property|Protected|Public|RaiseEvent|ReadOnly|ReDim|RemoveHandler|Resume|Return|Select|Set|Shadows|Shared|Short|Single|Static|Step|Stop|String|Structure|Sub|SyncLock|Then|Throw|To|Try|TypeOf|Unicode|Until|Variant|Wend|When|While|With|WithEvents|WriteOnly|Xor|EndIf|GoSub|Let|Variant|Wend)\b/i,
null],[PR.PR_COMMENT,/^REM[^\r\n\u2028\u2029]*/i],[PR.PR_LITERAL,/^(?:True\b|False\b|Nothing\b|\d+(?:E[+\-]?\d+[FRD]?|[FRDSIL])?|(?:&H[0-9A-F]+|&O[0-7]+)[SIL]?|\d*\.\d+(?:E[+\-]?\d+)?[FRD]?|#\s+(?:\d+[\-\/]\d+[\-\/]\d+(?:\s+\d+:\d+(?::\d+)?(\s*(?:AM|PM))?)?|\d+:\d+(?::\d+)?(\s*(?:AM|PM))?)\s+#)/i],[PR.PR_PLAIN,/^(?:(?:[a-z]|_\w)\w*|\[(?:[a-z]|_\w)\w*\])/i],[PR.PR_PUNCTUATION,/^[^\w\t\n\r "'\[\]\xA0\u2018\u2019\u201C\u201D\u2028\u2029]+/],[PR.PR_PUNCTUATION,/^(?:\[|\])/]]),["vb","vbs"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"]],[[PR.PR_STRING,/^(?:[BOX]?"(?:[^"]|"")*"|'.')/i],[PR.PR_COMMENT,/^--[^\r\n]*/],[PR.PR_KEYWORD,/^(?:abs|access|after|alias|all|and|architecture|array|assert|attribute|begin|block|body|buffer|bus|case|component|configuration|constant|disconnect|downto|else|elsif|end|entity|exit|file|for|function|generate|generic|group|guarded|if|impure|in|inertial|inout|is|label|library|linkage|literal|loop|map|mod|nand|new|next|nor|not|null|of|on|open|or|others|out|package|port|postponed|procedure|process|pure|range|record|register|reject|rem|report|return|rol|ror|select|severity|shared|signal|sla|sll|sra|srl|subtype|then|to|transport|type|unaffected|units|until|use|variable|wait|when|while|with|xnor|xor)(?=[^\w-]|$)/i,
null],[PR.PR_TYPE,/^(?:bit|bit_vector|character|boolean|integer|real|time|string|severity_level|positive|natural|signed|unsigned|line|text|std_u?logic(?:_vector)?)(?=[^\w-]|$)/i,null],[PR.PR_TYPE,/^'(?:ACTIVE|ASCENDING|BASE|DELAYED|DRIVING|DRIVING_VALUE|EVENT|HIGH|IMAGE|INSTANCE_NAME|LAST_ACTIVE|LAST_EVENT|LAST_VALUE|LEFT|LEFTOF|LENGTH|LOW|PATH_NAME|POS|PRED|QUIET|RANGE|REVERSE_RANGE|RIGHT|RIGHTOF|SIMPLE_NAME|STABLE|SUCC|TRANSACTION|VAL|VALUE)(?=[^\w-]|$)/i,null],[PR.PR_LITERAL,/^\d+(?:_\d+)*(?:#[\w\\.]+#(?:[+\-]?\d+(?:_\d+)*)?|(?:\.\d+(?:_\d+)*)?(?:E[+\-]?\d+(?:_\d+)*)?)/i],
[PR.PR_PLAIN,/^(?:[a-z]\w*|\\[^\\]*\\)/i],[PR.PR_PUNCTUATION,/^[^\w\t\n\r \xA0"'][^\w\t\n\r \xA0\-"']*/]]),["vhdl","vhd"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t \xA0a-gi-z0-9]+/,null,"\t \u00a0abcdefgijklmnopqrstuvwxyz0123456789"],[PR.PR_PUNCTUATION,/^[=*~\^\[\]]+/,null,"=*~^[]"]],[["lang-wiki.meta",/(?:^^|\r\n?|\n)(#[a-z]+)\b/],[PR.PR_LITERAL,/^(?:[A-Z][a-z][a-z0-9]+[A-Z][a-z][a-zA-Z0-9]+)\b/],["lang-",/^\{\{\{([\s\S]+?)\}\}\}/],["lang-",/^`([^\r\n`]+)`/],[PR.PR_STRING,/^https?:\/\/[^\/?#\s]*(?:\/[^?#\s]*)?(?:\?[^#\s]*)?(?:#\S*)?/i],[PR.PR_PLAIN,/^(?:\r\n|[\s\S])[^#=*~^A-Zh\{`\[\r\n]*/]]),["wiki"]);
PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_KEYWORD,/^#[a-z]+/i,null,"#"]],[]),["wiki.meta"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PUNCTUATION,/^[:|>?]+/,null,":|>?"],[PR.PR_DECLARATION,/^%(?:YAML|TAG)[^#\r\n]+/,null,"%"],[PR.PR_TYPE,/^[&]\S+/,null,"&"],[PR.PR_TYPE,/^!\S*/,null,"!"],[PR.PR_STRING,/^"(?:[^\\"]|\\.)*(?:"|$)/,null,'"'],[PR.PR_STRING,/^'(?:[^']|'')*(?:'|$)/,null,"'"],[PR.PR_COMMENT,/^#[^\r\n]*/,null,"#"],[PR.PR_PLAIN,/^\s+/,null," \t\r\n"]],[[PR.PR_DECLARATION,/^(?:---|\.\.\.)(?:[\r\n]|$)/],[PR.PR_PUNCTUATION,/^-/],[PR.PR_KEYWORD,/^\w+:[ \r\n]/],[PR.PR_PLAIN,/^\w+/]]),
["yaml","yml"]);_ds.u(VI,_ds.T);VI.prototype.whenReady=function(){return this.L.promise};
VI.prototype.connectedCallback=function(){var a=this,b;return _ds.E(function(c){switch(c.h){case 1:return _ds.w(c,DevsiteApp.whenReady(),2);case 2:return a.K||(XI(a),WI(a),a.K=!0),a.H.get("pref_dark-code")&&a.setAttribute("dark-code",""),a.L.resolve(),_ds.z(c,3),_ds.w(c,DevsiteApp.intersectionEnterForElement(a),5);case 5:_ds.B(c,4);break;case 3:if(b=_ds.C(c),"IntersectionObserver not supported"!==b.message)return c.return();case 4:var d=a.querySelector(".devsite-code-buttons-container");if(d)a.h=
d;else{a.h=_ds.Op(QI);a.hasAttribute("scope")&&(a.o=_ds.Op(UI,{label:"Open code sample in JSFiddle"}),(a.hasAttribute("jsfiddle-label")||a.hasAttribute("jsfiddle-title"))&&a.o.setAttribute("data-label",a.getAttribute("jsfiddle-label")||a.getAttribute("jsfiddle-title")),a.h.appendChild(a.o));a.C=_ds.Op(RI,{label:"Dark code theme"});a.h.appendChild(a.C);a.D=_ds.Op(SI,{label:"Light code theme"});a.h.appendChild(a.D);if(!a.hasAttribute("no-copy")){d=a.getAttribute("data-copy-event-label");var e="Click To Copy";
d&&(e+=": "+d);a.m=_ds.Op(TI,{label:a.G,vl:e});a.h.appendChild(a.m)}a.appendChild(a.h)}ZI(a);a.F=document.querySelector("devsite-snackbar");_ds.x(c)}})};VI.prototype.disconnectedCallback=function(){var a=this;return _ds.E(function(b){if(1==b.h)return _ds.w(b,DevsiteApp.whenReady(),2);DevsiteApp.unregisterIntersectionForElement(a);a.h&&a.removeChild(a.h);_ds.Hj(a.j);_ds.x(b)})};
VI.prototype.attributeChangedCallback=function(a,b,c){var d=this;return _ds.E(function(e){if(1==e.h){if("dark-code"!==a||b===c)return e.J(0);if(d.hasAttribute("dark-code"))return d.H.set("pref_dark-code","1"),_ds.w(e,_ds.zi(),6);d.H.remove("pref_dark-code");return _ds.w(e,_ds.zi(),5)}if(6!=e.h)return Array.from(document.querySelectorAll("devsite-code[dark-code]")).forEach(function(g){g.removeAttribute("dark-code")}),e.J(0);Array.from(document.querySelectorAll("devsite-code:not([dark-code])")).filter(function(g){return g!==
d}).forEach(function(g){g.setAttribute("dark-code","")});_ds.x(e)})};_ds.l.Object.defineProperties(VI,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return["dark-code"]}}});VI.prototype.attributeChangedCallback=VI.prototype.attributeChangedCallback;VI.prototype.disconnectedCallback=VI.prototype.disconnectedCallback;VI.prototype.connectedCallback=VI.prototype.connectedCallback;VI.prototype.whenReady=VI.prototype.whenReady;try{window.customElements.define("devsite-code",VI)}catch(a){console.warn("devsite.app.customElement.DevsiteCode",a)};})(_ds_www);
